# Generated by Django 3.1.7 on 2022-11-01 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLicenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_licenca', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LicencaAmbiental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=18)),
                ('rg', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=13)),
                ('ano_cadastro', models.DateTimeField()),
                ('data_inicio', models.DateTimeField()),
                ('data_vencimento', models.DateTimeField()),
                ('situacao', models.BooleanField()),
                ('numero_projeto', models.IntegerField()),
                ('cnpj', models.CharField(max_length=25)),
                ('arquivos', models.FileField(upload_to='Files/LicencaAmbiental')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenZ.cidade')),
                ('tipo_licenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenZ.tipolicenca')),
            ],
        ),
        migrations.CreateModel(
            name='CreditoRural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=18)),
                ('rg', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=13)),
                ('ano_cadastro', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('juros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('situacao', models.BooleanField()),
                ('data_pagamento', models.DateTimeField()),
                ('numero_projeto', models.IntegerField()),
                ('analise_previa', models.BooleanField()),
                ('atividade', models.CharField(max_length=100)),
                ('emissao_cedula', models.DateTimeField()),
                ('seguro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('linha_credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arquivos', models.FileField(upload_to='Files/CreditoRural')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenZ.banco')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenZ.cidade')),
            ],
        ),
    ]
