# Generated by Django 3.1.7 on 2022-11-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenZ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditorural',
            name='numero_projeto',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='licencaambiental',
            name='numero_projeto',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tipolicenca',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
