# Generated by Django 3.1.7 on 2022-11-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenZ', '0002_auto_20221107_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditorural',
            name='ano_cadastro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='creditorural',
            name='data_pagamento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='creditorural',
            name='emissao_cedula',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='licencaambiental',
            name='ano_cadastro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='licencaambiental',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='licencaambiental',
            name='data_vencimento',
            field=models.DateField(),
        ),
    ]
